#!/bin/bash
#
# Fetch and run me like this:
#
# wget https://raw.githubusercontent.com/elsampsa/darknet-python/master/bootstrap/darknet_py_ubuntu18_cuda_install
# chmod a+x darknet_py_ubuntu18_cuda_install
# ./darknet_py_ubuntu18_cuda_install
#
echo NOT UP TO DATE!
not-up-to-date
echo 
echo Downloading nvidia drivers and cuda.  This might take a while ..
echo
wget https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda-repo-ubuntu1804-10-0-local-10.0.130-410.48_1.0-1_amd64
echo
echo Installing nvidia drivers and cuda
echo
sudo dpkg -i cuda-repo-ubuntu1804-10-0-local-10.0.130-410.48_1.0-1_amd64
sudo apt-key add /var/cuda-repo-10-0-local-10.0.130-410.48/7fa2af80.pub
sudo apt-get update
sudo apt-get install cuda
echo
echo All good?
echo Time to reboot!
echo
