#!/usr/bin/python3
import re
import sys

# regex=re.compile("(\s\* Copyright (.|\n)* \*\/)")

# the old LGPL licensing
cp1=""" * Copyright 2017 Valkka Security Ltd. and Sampsa Riikonen.
 * 
 * Authors: Sampsa Riikonen <sampsa.riikonen@iki.fi>
 * 
 * This file is part of Valkka library.
 * 
 * Valkka is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Valkka is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with Valkka.  If not, see <http://www.gnu.org/licenses/>. 
 * 
"""

# AGPL licensing (since 2018) # removed the authors section from here ..
cp2=""" * Copyright 2017, 2018 Valkka Security Ltd. and Sampsa Riikonen.
 * 
 * This file is part of the Valkka library.
 * 
 * Valkka is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>
 *
"""

cpp=cp2

newlines=[]

fname=sys.argv[1]
f=open(fname,"r")
subs=False
for line in f:
  if (line.find("* Copyright")>-1):
    subs=True
  if (subs and (line.find("*/")>-1)):
    subs=False
    # print(cpp[0:-1])
    newlines.append(cpp)
    
  if (not subs):
    # print(line[0:-1])
    newlines.append(line)
  
f.close()

# f=open("paska.txt","w")
f=open(fname,"w")
for line in newlines:
  # print(line)
  f.write(line)
f.close()



